# Generated by Django 6.0.2 on 2026-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='dateLimit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
